CREATE DATABASE DBCARRITO
GO

USE DBCARRITO
GO

CREATE TABLE CATEGORIA(
IdCategoria INT PRIMARY KEY IDENTITY (1,1),
Descripcion VARCHAR(100),
Activo BIT DEFAULT 1,
FechaRegistro DATETIME DEFAULT GETDATE()
)

GO

CREATE TABLE MARCA(
IdMarca INT PRIMARY KEY IDENTITY(1,1),
Descripcion VARCHAR(100),
Activo BIT DEFAULT 1,
FechaRegisto DATETIME DAFAULT GETDATE()
)
GO

CREATE TABLE PRODUCTO(
IdProducto INT PRIMARY KEY IDENTITY(1,1),
Nombre VARCHAR(500),
Descripcion VARCHAR(500),
IdMarca INT, 
IdCategoria INT,
Precio DECIMAL(10,2) DEFAULT 0,
Stock INT,
RutaImagen VARCHAR(100),
NombreImagen VARCHAR(100),
Activo BIT DEFAULT 1,
FechaRegisto DATETIME DAFAULT GETDATE()
)